---
title: "Untitled"
output: html_document
date: "2025-05-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```


```{r}
library(tidyverse)
library(survey)
```

This R script obtains the direct estimations (ENDES) for the recategorized
indicators used downstream:
- edu: at least completed primary education (`hv109_recat`)
- wi:  at least in the 3rd wealth level (`hv270_recat`)

# 1. data ENDES from 2010-2020
```{r}
wi_edu_2010_2020 <-read.csv("./data/wi_edu_2010_2020.csv") %>% mutate(ubigeo = as.character(ubigeo))
```

# 2. Direct estimations with ENDES

```{r}
options(survey.lonely.psu = "adjust")

data_final_nest <-
  wi_edu_2010_2020 %>%
  mutate(hv005 = hv005 / 1000000) %>%
  group_by(year) %>%
  nest() %>%
  mutate(
    svydesign_endes = map(.x = data,
                          .f = ~svydesign(ids = ~hv001, strata = ~hv022,
                                          weights = ~hv005, data = .x, nest = T)),

    edu_directa_recat = map(.x = svydesign_endes,
                            .f = ~svyby(~hv109_recat, ~ubigeo, design = .x, svymean, keep.var = T)),

    wi_directa_recat = map(.x = svydesign_endes,
                           .f = ~svyby(~hv270_recat, ~ubigeo, design = .x, svymean, keep.var = T))
  )
```

# 3. Save district-level direct estimates (reference for 02 & 03)

```{r}
year_vec <- 2010:2020

edu_censo_final_recat <-
  map2_df(data_final_nest$edu_directa_recat, year_vec, ~ mutate(.x, year = .y)) %>%
  as_tibble() %>%
  select(year, ubigeo, hv109_recat, se)

wi_censo_final_recat <-
  map2_df(data_final_nest$wi_directa_recat, year_vec, ~ mutate(.x, year = .y)) %>%
  as_tibble() %>%
  select(year, ubigeo, hv270_recat, se)
```

```{r, echo=FALSE}
write.csv(edu_censo_final_recat, "./data/edu_censo_final_recat.csv", row.names = F)
write.csv(wi_censo_final_recat,  "./data/wi_censo_final_recat.csv",  row.names = F)
```

# 4. Save data for descriptive figure (fig1_data.csv, used in 06)

```{r}
df_final_edu <- map2_df(data_final_nest$edu_directa_recat, year_vec, ~ mutate(.x, year = .y)) %>%
  as_tibble() %>%
  rename(estimate = hv109_recat) %>%
  mutate(index = "edu") %>%
  select(year, ubigeo, index, everything())

df_final_wi <- map2_df(data_final_nest$wi_directa_recat, year_vec, ~ mutate(.x, year = .y)) %>%
  as_tibble() %>%
  rename(estimate = hv270_recat) %>%
  mutate(index = "wi") %>%
  select(year, ubigeo, index, everything())

df_final <-
  bind_rows(df_final_edu, df_final_wi) %>%
  filter(year %in% c(2010,2012,2014,2016,2018,2020))

write.csv(df_final, "./data/aux_data/fig1_data.csv", row.names = F)
```
