---
title: "Untitled"
output: html_document
date: "2025-06-06"
---

```{r, message=F, warning=F}
library(tidyverse)
library(sf)
library(sf)
library(biscale)
library(janitor)
library(innovar)
library(cowplot)
library(ggmagnify)
library(magick)

source("./_functions/functions.R")
```


```{r}
wi_sae_m3  <- read.csv("./data/final_data/wi_pred_m3_pc1.csv")  %>%
  mutate(ubigeo = as.character(ubigeo))
edu_sae_m3 <- read.csv("./data/final_data/edu_pred_m3_pc1.csv") %>%
  mutate(ubigeo = as.character(ubigeo))

data("Peru")

distritos <- Peru %>% filter(dep == "LORETO") %>% mutate(ubigeo = as.character(ubigeo))
```

```{r}
df_final<- read.csv("./data/aux_data/fig1_data.csv")

```


```{r, warning=F, message=F}
malaria_dist_total <- read_csv("./data/aux_data/malaria_dist_total.csv") %>% 
  mutate(
    ubigeo = as.character(ubigeo)
  ) %>% 
  clean_names() %>% 
  filter(year %in% c(2010:2020)) %>% 
  right_join(distritos) %>% 
  st_as_sf() %>% 
  mutate(
    malaria_incidence = ifelse(is.na(malaria_incidence),0,malaria_incidence)
  )

malaria_dist_specie <- read_csv("data/aux_data/malaria_dist_species.csv") %>% 
  mutate(
    ubigeo = as.character(ubigeo)
  ) %>% 
  clean_names() %>% 
  right_join(distritos) %>% 
  st_as_sf() %>% 
    mutate(
    malaria_incidence = ifelse(is.na(malaria_incidence),0,malaria_incidence)
  )

```

# MALARIA -----

```{r}

g<-wi_edu %>% 
  select(year, hv001, long, lat) %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326, remove = FALSE) %>% 
  group_by(year, hv001) %>% 
  summarise(
    n = n(),
    .groups = "drop"
  ) %>% 
  mutate(
    year_cat = ifelse(year <=2014,"1st","2nd"),
    
    year_cat = factor(year_cat, levels = c("1st","2nd"),
                      labels = c("2010-2014 period (40-50 PSU by year)",
                                 '2015-2020 period (>100 PSU by year)')),
    year_cat_2 = as.factor(year),
    n_cat = ntile(n, 5)
  )
g <- st_cast(g, "POINT")

 psu_map<-
   ggplot() +
  geom_sf(data = distritos, color = "white",fill = "grey92",linewidth = 0.3) +
  geom_sf(data = g, aes(color = year_cat), size = 1, alpha = 0.5) +
  scale_color_manual(
    values = c("2010-2014 period (40-50 PSU by year)" = "#E69F00",
               "2015-2020 period (>100 PSU by year)"   = "#0072B2")
    
  ) +
         coord_sf(expand = FALSE) +
  labs(
    col = NULL
  ) +
  
  theme_void() +
    theme(
      legend.position = "bottom",
      plot.margin = unit(c(0, 0, 0, 0), "cm")
    )

 
 peru_dist <- Peru
peru_mini <- 
peru_dist %>%
  mutate(
    loreto_col = ifelse(dep.code == "16","1","0")
  ) %>% 
  ggplot() +
  
  geom_sf(data = peru_dist %>%
            st_union() %>%
            st_as_sf(), 
          
          fill = NA, 
          color = "black", 
          size = 1) +
  
  geom_sf(aes(fill = loreto_col, col = loreto_col)) +

  scale_color_manual(values = c("1" = "grey50",
                                "0" = "grey90")) +
  scale_fill_manual(values = c("1" = "grey50",
                                "0" = "grey90")) +
  guides(fill = "none", col = "none") +
  theme_void()

######
logo <- image_read("./flecha-curva.png")

peru_loreto<-
ggdraw() +
  draw_plot(psu_map) +
  draw_plot(peru_mini, 
            x = 0.08, y = 0.15, 
            width = 0.20, height = 0.30) +
  draw_image(logo, 
             x = 0.18, y = 0.45, 
             width = 0.1, height = 0.1)

peru_loreto
#ggsave("./figures/sup_result_fig1.png", dpi = 800, bg = "white", height = 10, width = 14)
```


```{r}
loreto_malaria_area<-
  malaria_dist_total %>% 
  group_by(year,prov) %>% 
  summarise(meanincidence = mean(malaria_incidence)) %>% 
  ungroup() %>% 
  st_drop_geometry() %>% 
  
  ggplot(aes(x = year, y = meanincidence, fill = prov)) +
  
  geom_area(alpha=0.5 , size=.5) +
  ggsci::scale_fill_nejm() +
  
  labs(fill = "Provinces\n(admin level-2)",
       y = "malaria incidence x 1000 inhab.",
       x = "year") +
  
  scale_x_continuous(limits = c(2010,2020), breaks = seq(2010,2020,2)) +
  
  theme_minimal() +
  
  theme(
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 7),
    axis.title = element_text(face = "bold"),
    panel.grid.major  = element_blank()
  )

legend_prov <- gtable::gtable_add_padding(
  get_legend2(loreto_malaria_area),
  padding = unit(c(1, 0, 0, 1), "cm")  # top, right, bottom, left
)

loreto_malaria_area_nolegend<-loreto_malaria_area + theme(legend.position = "none")
```

```{r}
peru_prov<-
malaria_dist_total %>%
  filter(year == 2010) %>% 
  ggplot() +
  geom_sf(aes(fill = prov),alpha = .5) +
  ggsci::scale_fill_nejm() +
  guides(fill = "none") +
  theme_void()
```


```{r}
malaria_prov_map<-
  plot_grid(
plot_grid(peru_prov,loreto_malaria_area_nolegend,
          rel_widths = c(1.1,1)),

legend_prov, nrow = 2, rel_heights = c(1,.1))

```

```{r}
malaria_maps<-
  malaria_dist_total %>% 
  #filter(year%in%c(2010,2012,2014,2016,2018,2020)) %>% 
  ggplot() +
  geom_sf(aes(fill = log10(malaria_incidence))) +
  
  facet_wrap(~year, nrow = 3) +
  theme_void() +
scale_fill_gradientn(
    colours = rev(RColorBrewer::brewer.pal(11, "RdBu")), # rojo alto, azul bajo
    #limits = c(-1.5, 4),        # según tus valores
    #values = scales::rescale(c(-1.5, 0, 4)), # 0 al centro
    oob = scales::squish,
    na.value = "gray80",
    name = "log10(Malaria incidence x 1000 inhab.)"
  ) +
  guides(fill = guide_colourbar(barheight = .5, 
                                barwidth = 14,
                                title.position = "top",
                                direction = "horizontal")) +
  
  theme(
    #legend.position = c(.45,.15),
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    plot.margin = unit(c(1, 0, 0, 0), "cm")
  )
malaria_maps
#ggsave("./figures/test2.png", dpi = 800, bg = "white", width = 10)

ggsave("./figures/sup_result_fig1b.pdf", dpi = 800, bg = "white", width = 10)
```

```{r}
plot_grid(plot_grid(peru_loreto,
          
          malaria_prov_map, nrow = 1, labels = c("a","b"), rel_widths = c(.9,1)  ),
          
          malaria_maps,
          
          
          ncol = 1, rel_heights = c(1,1), labels = c("","c"))
```

```{r}
  ggsave("./figures/fig1.pdf", dpi = 800, bg = "white", width = 14, height= 6)
```

# INDICE RIQUEZA -----
```{r}
data_wi <-
  malaria_dist_total %>%
  mutate(ubigeo = as.character(ubigeo)) %>%
  full_join(wi_sae_m3, by = c('year', 'ubigeo')) %>%
  mutate(year = as.character(year))

data_wi2 <-
  malaria_dist_specie %>%
  mutate(ubigeo = as.character(ubigeo)) %>%
  full_join(wi_sae_m3, by = c('year', 'ubigeo')) %>%
  mutate(year = as.character(year))



```


```{r}
data_bi <- bi_class(data_wi, y = median, x = malaria_incidence, dim = 3, style = "quantile")

data_bi2 <- bi_class(data_wi2, y = median, x = malaria_incidence, dim = 3, style = "quantile")
```


```{r}
map <- 
  ggplot() +
  geom_sf(data = data_bi %>% 
            filter(year %in% c(2010,2012,2014,2016,2018,2020)),
          mapping = aes(fill = bi_class), color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkViolet", dim = 3) +
 theme_void() +
  facet_wrap(~year, nrow = 1) +
  
  theme(
    strip.text = element_text(face = "bold")
  )
```


```{r}
map2<-
  ggplot() +
  geom_sf(data = data_bi2 %>% 
            filter(year %in% c(2010,2013,2017,2020)),
          mapping = aes(fill = bi_class), color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  theme_void() +
  facet_grid(enfermedad~year)
```


```{r}
legend <- bi_legend(pal = "DkViolet",
                    dim = 3,
                    xlab = "malaria incidence",
                    ylab = "% Poverty",
                    size = 7)
```


```{r}
bimap_wi<-
  ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +
  draw_plot(legend, 0.42, .7, 0.20, 0.3) 
```


```{r}
bimap_wi_species<-
  ggdraw() +
  draw_plot(map2, 0, 0, 1, 1) +
  draw_plot(legend, 0.65, .08, 0.13, 0.15)
```


```{r}
#ggsave("./figures/fig8.png", dpi = 300, bg = "white", width = 9, height = 10)

```

## Moran bivariate

```{r}
library(spdep)
library(sfdep)

moran_test <-
  data_wi %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(
    nb = map(.x = data,
             .f = ~poly2nb(.x, queen = T)),
    
    lw = map(.x = nb,
             .f = ~nb2listw(.x, style = "W", zero.policy = T)),
    
    wt = map(.x = lw, .f = ~.x$weights),
    
    moranbi = map2(.x = data, .y = lw,
                   .f = ~moran_bv(x = .x$malaria_incidence, 
                                  y = .x$median, listw = .y, nsim = 999, scale = T)),
    
    morant = map2(.x = data, .y = lw,
                  .f = ~moran.test(x = .x$malaria_incidence, .y, alternative = "greater")),
    
    localmoran = map2(.x = data, .y = lw,
                      .f = ~localmoran(x = .x$malaria_incidence, .y, alternative = "greater")),
    
    # Use pmap to pass multiple arguments (data, nb, and lw)
    localmoran_bi = pmap(list(data, nb, wt),
                         ~ local_moran_bv(x = ..1$malaria_incidence, 
                                          y = ..1$median, 
                                          nb = ..2, 
                                          wt = ..3, nsim = 999)),
    
    
    
    lisa_classified = pmap(list(data, localmoran_bi, lw),
                          function(df, lisa, listw) {
                            # Estandarizar la variable X (malaria)
                            z_malaria <- scale(df$malaria_incidence)[,1]
                            
                            # Calcular el lag espacial de Y (edu) manualmente
                            lag_edu <- lag.listw(listw, df$median)
                            
                            # Estandarizar el lag
                            z_lag_edu <- scale(lag_edu)[,1]
                            
                            # Crear el dataframe con clasificación
                            df %>%
                              mutate(
                                Ib = lisa$Ib,
                                p_sim = lisa$p_sim,
                                z_malaria = z_malaria,
                                z_lag_edu = z_lag_edu,
                                
                                # Clasificar en cuadrantes
                                quadrant = case_when(
                                  z_malaria >= 0 & z_lag_edu >= 0 ~ "High-High",
                                  z_malaria < 0 & z_lag_edu < 0 ~ "Low-Low",
                                  z_malaria >= 0 & z_lag_edu < 0 ~ "High-Low",
                                  z_malaria < 0 & z_lag_edu >= 0 ~ "Low-High"
                                ),
                                
                                # Solo significativos
                                quadrant_sig = if_else(p_sim < 0.05, 
                                                       quadrant, 
                                                       "Not significant")
                              )
                          })
  )


moran_test$moranbi
```


```{r}
lisa_wi<-
  moran_test %>% 
  select(year,data,localmoran_bi,lisa_classified) %>% 
  unnest() %>% 
  ungroup() %>% 
  st_as_sf() %>% 
  select(year,ubigeo,malaria_incidence,median,Ib,p_sim,quadrant) %>% 
  filter(year %in% c(2010,2012,2014,2016,2018,2020)) %>% 
  mutate(
    sig = ifelse(p_sim<=0.05,'si','no')
  ) %>% 
  
  ggplot() +
  geom_sf(aes(fill = quadrant, alpha = sig), col = "grey") +
  
  scale_alpha_manual(guide = "none", values = c('si' = 1,
                                                'no' = .2)) +
  
  scale_fill_manual(values = c("Low-Low" = "#1F78B4",
                               "High-Low"="#FDBF6F",
                               "High-High"="#E31A1C",
                               "Low-High"="#A6CEE3",
                               "Not significant" = "grey50"
                               
                               ), name = "LISA clusters"
                    ) +

  theme_void() +
  
  facet_wrap(~year, nrow = 1) +
  
  theme(
    strip.text = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    plot.margin = unit(c(0, 0, 0, 0), "cm")
  )

```

```{r}
plot_grid(
  
  plot_grid(legend,map, nrow = 2, rel_heights = c(.6,1)),
  
  lisa_wi, nrow = 2, labels = c("a","b"))

ggsave("./figures/fig7.pdf", dpi = 800, bg = "white", width = 12, height = 7)
```

# EDUCACION -----
```{r}
data_edu <-
  malaria_dist_total %>%
  mutate(ubigeo = as.character(ubigeo)) %>%
  full_join(edu_sae_m3, by = c('year', 'ubigeo')) %>%
  mutate(year = as.character(year))

data_edu2 <-
  malaria_dist_specie %>%
  mutate(ubigeo = as.character(ubigeo)) %>%
  full_join(edu_sae_m3, by = c('year', 'ubigeo')) %>%
  mutate(year = as.character(year))
```


```{r}
data_bi <- bi_class(data_edu, y = median, x = malaria_incidence, dim = 3, style = "quantile")

data_bi2 <- bi_class(data_edu2, y = median, x = malaria_incidence, dim = 3, style = "quantile")
```


```{r}
map <- 
  ggplot() +
  geom_sf(data = data_bi %>% 
            filter(year %in% c(2010,2012,2014,2016,2018,2020)),
          mapping = aes(fill = bi_class), color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  labs(
    #title = "Malaria incidence distribution across education level"
  ) +
 theme_void() +
  facet_wrap(~year, nrow = 1) +
  
  theme(
    strip.text = element_text(face = "bold")
  )


```


```{r}
map2<-
  ggplot() +
  geom_sf(data = data_bi2 %>% 
            filter(year %in% c(2010,2012,2014,2016,2018,2020)),
          mapping = aes(fill = bi_class), color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  theme_void() +
  facet_grid(enfermedad~year)
```


```{r}
legend <- bi_legend(pal = "DkViolet",
                    dim = 3,
                    xlab = "malaria incidence",
                    ylab = "% Element. education",
                    size = 7)
```


```{r}
bimap_edu<-
  ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +
  draw_plot(legend, 0.42, .7, 0.20, 0.3) 
```

```{r}
ggdraw() +
  draw_plot(map2, 0, 0, 1, 1) +
  draw_plot(legend, 0.65, .08, 0.13, 0.15)
```

```{r}
#ggsave("./figures/fig9.png", dpi = 300, bg = "white", width = 9, height = 10)
```

## Moran bivariate

```{r}
library(spdep)
library(sfdep)

moran_test_edu <-
  data_edu %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(
    nb = map(.x = data,
             .f = ~poly2nb(.x, queen = T)),
    
    lw = map(.x = nb,
             .f = ~nb2listw(.x, style = "W", zero.policy = T)),
    
    wt = map(.x = lw, .f = ~.x$weights),
    
    moranbi = map2(.x = data, .y = lw,
                   .f = ~moran_bv(x = .x$malaria_incidence, 
                                  y = .x$median, listw = .y, nsim = 999, scale = T)),
    
    morant = map2(.x = data, .y = lw,
                  .f = ~moran.test(x = .x$malaria_incidence, .y, alternative = "greater")),
    
    localmoran = map2(.x = data, .y = lw,
                      .f = ~localmoran(x = .x$malaria_incidence, .y, alternative = "greater")),
    
    # Use pmap to pass multiple arguments (data, nb, and lw)
    localmoran_bi = pmap(list(data, nb, wt),
                         ~ local_moran_bv(x = ..1$malaria_incidence, 
                                          y = ..1$median, 
                                          nb = ..2, 
                                          wt = ..3, nsim = 999)),
    
    
    
    lisa_classified = pmap(list(data, localmoran_bi, lw),
                          function(df, lisa, listw) {
                            # Estandarizar la variable X (malaria)
                            z_malaria <- scale(df$malaria_incidence)[,1]
                            
                            # Calcular el lag espacial de Y (edu) manualmente
                            lag_edu <- lag.listw(listw, df$median)
                            
                            # Estandarizar el lag
                            z_lag_edu <- scale(lag_edu)[,1]
                            
                            # Crear el dataframe con clasificación
                            df %>%
                              mutate(
                                Ib = lisa$Ib,
                                p_sim = lisa$p_sim,
                                z_malaria = z_malaria,
                                z_lag_edu = z_lag_edu,
                                
                                # Clasificar en cuadrantes
                                quadrant = case_when(
                                  z_malaria >= 0 & z_lag_edu >= 0 ~ "High-High",
                                  z_malaria < 0 & z_lag_edu < 0 ~ "Low-Low",
                                  z_malaria >= 0 & z_lag_edu < 0 ~ "High-Low",
                                  z_malaria < 0 & z_lag_edu >= 0 ~ "Low-High"
                                ),
                                
                                # Solo significativos
                                quadrant_sig = if_else(p_sim < 0.05, 
                                                       quadrant, 
                                                       "Not significant")
                              )
                          })
  )
```


```{r}
lisa_edu<-
  moran_test_edu %>% 
  select(year,data,localmoran_bi,lisa_classified) %>% 
  unnest() %>% 
  ungroup() %>% 
  st_as_sf() %>% 
  select(year,ubigeo,malaria_incidence,median,Ib,p_sim,quadrant) %>% 
  filter(year %in% c(2010,2012,2014,2016,2018,2020)) %>% 
  mutate(
    sig = ifelse(p_sim<=0.05,'si','no')
  ) %>% 
  
  ggplot() +
  geom_sf(aes(fill = quadrant, alpha = sig),col = "grey") +
  
  scale_alpha_manual(guide = "none", values = c('si' = 1,
                                                'no' = .2)) +
  
  scale_fill_manual(values = c("Low-Low" = "#1F78B4",
                               "High-Low"="#FDBF6F",
                               "High-High"="#E31A1C",
                               "Low-High"="#A6CEE3",
                               "Not significant" = "grey50"
                               
                               ), name = "LISA clusters"
                    ) +

  theme_void() +
  
  facet_wrap(~year, nrow = 1) +
  
  theme(
    strip.text = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  )


```

```{r}
plot_grid(
  
  plot_grid(legend,map, nrow = 2, rel_heights = c(.6,1)),
  
  lisa_edu, nrow = 2, labels = c("a","b"))

ggsave("./figures/fig6.pdf", dpi = 800, bg = "white", width = 12, height = 7)
```

```{r}
# sup_result_fig1 — estimaciones directas ambos indicadores, todos los años
df %>%
  dplyr::mutate(lowic = estimate - 1.96*se, uppwic = estimate + 1.96*se,
         ubigeo = as.character(ubigeo)) %>%
  ggplot(aes(y = estimate, x = ubigeo)) +
  geom_pointrange(aes(ymin = lowic, ymax = uppwic, col = as.factor(index)),
                  linewidth = .5, alpha = .4) +
  scale_color_manual(values = c("edu" = "red4", "wi" = "blue4"),
                     labels = c("edu" = "Elementary education", "wi" = "Poverty status")) +
  labs(col = NULL, x = "Districts", y = "Direct estimates") +
  theme_minimal() +
  theme(axis.text.y = element_blank(), axis.title = element_text(face = "bold"),
        legend.position = "bottom", axis.ticks = element_blank(),
        panel.border = element_blank(), panel.grid.major.x = element_blank()) +
  facet_wrap(~year, ncol = 4) +
  coord_flip()

#ggsave("./figures/sup_result_fig1.pdf", dpi = 800, bg = "white", height = 12, width = 14)
```

```{r}
# sup_result_fig2 — mapas incidencia malaria, todos los años
malaria_dist_total %>%
  ggplot() +
  geom_sf(aes(fill = log10(malaria_incidence))) +
  facet_wrap(~year, nrow = 2) +
  scale_fill_gradientn(
    colours = rev(RColorBrewer::brewer.pal(11, "RdBu")),
    oob = scales::squish, na.value = "gray80",
    name = "log10(Malaria incidence x 1000 inhab.)"
  ) +
  guides(fill = guide_colourbar(barheight = .5, barwidth = 14,
                                title.position = "top", direction = "horizontal")) +
  theme_void() +
  theme(legend.position = "bottom", legend.title = element_text(face = "bold"))

ggsave("./figures/sup_result_fig2.pdf", dpi = 800, bg = "white", width = 14, height = 6)
```

```{r}
# sup_result_fig6 — biscale + LISA educacion, todos los años
map_sup6 <- ggplot() +
  geom_sf(data = data_bi, mapping = aes(fill = bi_class),
          color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  theme_void() + facet_wrap(~year, nrow = 2)

legend_sup6 <- bi_legend(pal = "DkViolet", dim = 3,
                         xlab = "malaria incidence", ylab = "% Element. education", size = 7)

lisa_sup6 <-
  moran_test_edu %>%
  select(year, data, localmoran_bi, lisa_classified) %>%
  unnest() %>% ungroup() %>% st_as_sf() %>%
  select(year, ubigeo, malaria_incidence, median, Ib, p_sim, quadrant) %>%
  mutate(sig = ifelse(p_sim <= 0.05, 'si', 'no')) %>%
  ggplot() +
  geom_sf(aes(fill = quadrant, alpha = sig), col = "grey") +
  scale_alpha_manual(guide = "none", values = c('si' = 1, 'no' = .2)) +
  scale_fill_manual(values = c("Low-Low" = "#1F78B4", "High-Low" = "#FDBF6F",
                               "High-High" = "#E31A1C", "Low-High" = "#A6CEE3",
                               "Not significant" = "grey50"), name = "LISA clusters") +
  theme_void() + facet_wrap(~year, nrow = 2) +
  theme(strip.text = element_blank(), legend.position = "bottom",
        legend.title = element_text(face = "bold"))

plot_grid(plot_grid(legend_sup6, map_sup6, nrow = 2, rel_heights = c(.3, 1)),
          lisa_sup6, nrow = 2, labels = c("a", "b"))

ggsave("./figures/sup_result_fig6.pdf", dpi = 800, bg = "white", width = 14, height = 14)
```

```{r}
# sup_result_fig7 — biscale + LISA poverty, todos los años
data_bi_wi <- bi_class(data_wi, y = median, x = malaria_incidence, dim = 3, style = "quantile")

map_sup7 <- ggplot() +
  geom_sf(data = data_bi_wi, mapping = aes(fill = bi_class),
          color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  theme_void() + facet_wrap(~year, nrow = 2)

legend_sup7 <- bi_legend(pal = "DkViolet", dim = 3,
                         xlab = "malaria incidence", ylab = "% Poverty", size = 7)

lisa_sup7 <-
  moran_test %>%
  select(year, data, localmoran_bi, lisa_classified) %>%
  unnest() %>% ungroup() %>% st_as_sf() %>%
  select(year, ubigeo, malaria_incidence, median, Ib, p_sim, quadrant) %>%
  mutate(sig = ifelse(p_sim <= 0.05, 'si', 'no')) %>%
  ggplot() +
  geom_sf(aes(fill = quadrant, alpha = sig), col = "grey") +
  scale_alpha_manual(guide = "none", values = c('si' = 1, 'no' = .2)) +
  scale_fill_manual(values = c("Low-Low" = "#1F78B4", "High-Low" = "#FDBF6F",
                               "High-High" = "#E31A1C", "Low-High" = "#A6CEE3",
                               "Not significant" = "grey50"), name = "LISA clusters") +
  theme_void() + facet_wrap(~year, nrow = 2) +
  theme(strip.text = element_blank(), legend.position = "bottom",
        legend.title = element_text(face = "bold"))

plot_grid(plot_grid(legend_sup7, map_sup7, nrow = 2, rel_heights = c(.3, 1)),
          lisa_sup7, nrow = 2, labels = c("a", "b"))

ggsave("./figures/sup_result_fig7.pdf", dpi = 800, bg = "white", width = 14, height = 14)
```


```{r}

```

